root        : INFO     Namespace(cuda=True, dataset_dir='../../dataset/', filename='main_pytorch', iteration_max=40000, mode='train', subdir='models_dev', validate=True, workspace='../../experiment_workspace/Conformer-1/')
root        : INFO     The data contains: 700 training and 300 validation data.
Traceback (most recent call last):
  File "main_pytorch.py", line 342, in <module>
    train(args)
  File "main_pytorch.py", line 172, in train
    cuda=cuda)
  File "main_pytorch.py", line 48, in evaluate
    cuda=cuda)
  File "main_pytorch.py", line 99, in forward
    batch_output = model(batch_x,batch_ch,batch_3)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dstore/home/tzhou/Conformer-1/main/models_pytorch.py", line 363, in forward
    output3, encoder_output_length_3 = self.conformer_encoder3(x3, x3.shape[-1])# (batch_size, time_steps, channels)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dstore/home/tzhou/ConformerSource/conformer-main/conformer/encoder.py", line 198, in forward
    outputs, output_lengths = self.conv_subsample(inputs, input_lengths)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dstore/home/tzhou/ConformerSource/conformer-main/conformer/convolution.py", line 177, in forward
    outputs = self.sequential(inputs.unsqueeze(1))
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 102, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/functional.py", line 1206, in relu
    result = torch.relu(input)
RuntimeError: CUDA out of memory. Tried to allocate 38.00 MiB (GPU 0; 10.92 GiB total capacity; 4.12 GiB already allocated; 36.44 MiB free; 4.15 GiB reserved in total by PyTorch)
root        : INFO     Namespace(cuda=True, dataset_dir='../../dataset/', filename='main_pytorch', iteration_max=40000, mode='inference_validation_data', subdir='models_dev', validate=True, workspace='../../experiment_workspace/Conformer-1/')
root        : INFO     The data contains: 700 training and 300 validation data.
param number:
70939202
Traceback (most recent call last):
  File "main_pytorch.py", line 345, in <module>
    inference_validation_data(args)
  File "main_pytorch.py", line 275, in inference_validation_data
    cuda=cuda)
  File "main_pytorch.py", line 99, in forward
    batch_output = model(batch_x,batch_ch,batch_3)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dstore/home/tzhou/Conformer-1/main/models_pytorch.py", line 325, in forward
    x2 = self.cnn_encoder2(x2)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dstore/home/tzhou/Conformer-1/main/models_pytorch.py", line 398, in forward
    x = self.conv1(x, pool_size=(2, 2), pool_type='avg')
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dstore/home/tzhou/Conformer-1/main/models_pytorch.py", line 81, in forward
    x = F.relu_(self.bn2(self.conv2(x)))
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 10.92 GiB total capacity; 4.11 GiB already allocated; 32.44 MiB free; 4.15 GiB reserved in total by PyTorch)
